# Generated by Django 5.1 on 2024-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_address_profile_getimg_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='profile',
            name='output_format',
            field=models.CharField(default='jpeg', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='width',
            field=models.IntegerField(default=1280),
        ),
    ]
