# Generated by Django 5.1 on 2024-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_height_profile_output_format_profile_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='response_format',
            field=models.CharField(default='image', max_length=255),
        ),
    ]
