# Generated by Django 5.1 on 2024-08-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_response_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='response_format',
        ),
    ]
